# Server Config
MODE: "release"
PORT: 8080

# Database Config
DATABASE:
  USERNAME: "root"
  PASSWORD: "password"
  NETWORK: "tcp"
  SERVER: "127.0.0.2"
  PORT: 3306
  DATABASE: "crms"

# Token Config
ADMIN:
  USERNAME: "admin"
  PASSWORD: "password"